services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    # env_file:
      # - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1738
      POSTGRES_DB: financedb
      # Use md5 authentication instead of scram-sha-256 for compatibility
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
